-- 코드를 입력하세요
# SELECT YEAR, MONTH, PUCHASED_USERS, PUCHASED_RATIO
# FROM USER_INFO JOIN ONLINE_SALE
# WHERE 
# ORDER BY YEAR, MONTH DESC

SELECT YEAR, MONTH, COUNT(U.USER_ID) AS PUCHASED_USERS, ROUND((COUNT(*) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021)), 1) AS PUCHASED_RATIO
FROM 
(SELECT USER_ID FROM USER_INFO WHERE YEAR(JOINED) = 2021) AS U 
JOIN
(SELECT DISTINCT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH FROM ONLINE_SALE) AS O 
ON U.USER_ID = O.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH

# 전체 회원 수
