-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME, 'O' AS '중성화'
FROM ANIMAL_INS 
WHERE SEX_UPON_INTAKE LIKE '%Neutered%' OR SEX_UPON_INTAKE LIKE '%Spayed%'

UNION

SELECT ANIMAL_ID, NAME, 'X' AS '중성화'
FROM ANIMAL_INS 
WHERE SEX_UPON_INTAKE NOT LIKE '%Neutered%' AND SEX_UPON_INTAKE NOT LIKE '%Spayed%'
ORDER BY ANIMAL_ID