SELECT DISTINCT R.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS R 
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON R.CAR_ID = H.CAR_ID
WHERE MONTH(H.START_DATE) = 10 AND R.CAR_TYPE = '세단'
ORDER BY R.CAR_ID DESC