SELECT b.TITLE,	b.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, date_format(r.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD b JOIN USED_GOODS_REPLY r
ON b.BOARD_ID = r.BOARD_ID
WHERE year(b.CREATED_DATE)=2022 and month(b.CREATED_DATE)=10
ORDER BY r.CREATED_DATE, b.TITLE;