-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') AS DATE_OF_BIRTH
FROM MEMBER_PROFILE 
WHERE GENDER = 'W' AND TO_NUMBER(to_char(DATE_OF_BIRTH, 'MM')) = 3 AND TLNO IS NOT NULL
ORDER BY MEMBER_ID

